version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
    command: serve -s dist

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/404.html:/usr/share/nginx/html/404.html
    depends_on:
      - app
